name: Docker Debian Slim

on:
  push:
    paths:
      - "Dockerfile"
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: rzlamrr
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: rzlamrr/rail:latest

